
- name: Create user group
  group: name={{ rdp_user }} state=present

- name: Create user
  user: name={{ rdp_user }} groups={{ rdp_user_group }} state=present shell=/bin/bash

- name: Home directory
  file: path={{ rdp_user_home }} state=directory owner={{ rdp_user }} group={{ rdp_user_group }}

- name: Scripts directory
  file: path={{ rdp_scripts_dir }} state=directory owner={{ rdp_user }} group={{ rdp_user_group }}

- name: Bin directory
  file: path={{ rdp_bin_dir }} state=directory owner={{ rdp_user }} group={{ rdp_user_group }}

- name: Env directory
  file: path={{ rdp_env_dir }} state=directory owner={{ rdp_user }} group={{ rdp_user_group }}

- name: Copy scripts
  copy: src=../../scripts/ dest={{ rdp_scripts_dir }} owner={{ rdp_user }} group={{ rdp_user_group }} mode=preserve

- name: Install packages
  apt:
    name:
      - p7zip-full
      - unzip
      - cron-apt
