
- name: Create user group
  group: name={{ rdp_user }} state=present

- name: Create user
  user: name={{ rdp_user }} groups={{ rdp_user_group }} state=present shell=/bin/bash

- name: Home directory
  file: path={{ rdp_user_home }} state=directory owner={{ rdp_user }} group={{ rdp_user_group }}

- name: Scripts directory
  file: path={{ rdp_scripts_dir }} state=directory owner={{ rdp_user }} group={{ rdp_user_group }}

- name: Bin directory
  file: path={{ rdp_bin_dir }} state=directory owner={{ rdp_user }} group={{ rdp_user_group }}

- name: Copy scripts
  copy: src=../../scripts/ dest={{ rdp_scripts_dir }} owner={{ rdp_user }} group={{ rdp_user_group }} mode=preserve

- name: Make sure 7zip is installed
  apt: name=p7zip-full state=latest

- name: Add cron script
  template: src=restore.sh dest={{ rdp_bin_dir }}/restore.sh owner={{ rdp_user }} group={{ rdp_user_group }} mode=0755

- name: Ensure Cron is installed
  apt: name=cron-apt state=present

- name: Setup cron
  cron: name="Restore DBs" minute="{{ rdp_restore_cron_minute }}" hour="{{ rdp_restore_cron_hour }}" weekday="{{ rdp_restore_cron_weekday }}" user="{{ rdp_restore_cron_user }}" job="{{ rdp_bin_dir }}/restore.sh"
