rdp_backup_user: "rdp"
rdp_backup_group: "{{ rdp_backup_user }}"
rdp_backup_home_dir: "/home/{{ rdp_backup_user }}"
rdp_backup_log_file: "/var/log/{{ rdp_backup_user }}.log"
rdp_backup_scripts_dir: "{{ rdp_backup_home_dir }}/scripts"
rdp_backup_target_dir: "{{ rdp_backup_home_dir }}/backup"
rdp_backup_postgres_user: "postgres"
rdp_backup_postgres_database: "dhis"
rdp_backup_file_password: "Test1234"
rdp_backup_file_path: "{{ rdp_backup_target_dir }}/{{ rdp_backup_postgres_database }}.pgdump.7z"
rdp_backup_cron_hour: "2"
rdp_backup_cron_minute: "0"
rdp_backup_cron_weekday: "0-6"
rdp_backup_cron_user: "root"
