rdp_backup_cron_hour: "7"
rdp_backup_cron_minute: "9"
rdp_restore_cron_hour: "15"
rdp_restore_cron_minute: "3"

rdp_backup_dbs:
  - backupId: "openmrs"
    backupType: "xtrabackup"
    mysqlUser: "root"
    mysqlPassword: "root"
    mysqlDataDir: "/var/lib/mysql"
    mysqlRunDir: "/var/run/mysqld"
    targetDataDir: "{{ rdp_backup_db_dir }}/openmrs/targetDataDir"
    backupFilePassword: "Test1234"
    backupFilePath: "{{ rdp_backup_db_dir }}/openmrs/openmrs.xtrabackup.7z"

  - backupId: "dhis"
    backupType: "pgdump"
    postgresUser: "postgres"
    postgresDatabase: "dhis"
    postgresContainerName: ""
    backupFilePassword: "Test1234"
    backupFilePath: "{{ rdp_backup_db_dir }}/dhis/dhis.pgdump.7z"

rdp_transfer_files:
  - sourceFile: "{{ rdp_backup_db_dir }}/openmrs/openmrs.xtrabackup.7z"
    targetFile: "{{ rdp_user_home }}/archive/openmrs.xtrabackup.7z"

  - sourceFile: "{{ rdp_backup_db_dir }}/openmrs/openmrs.xtrabackup.7z.md5"
    targetFile: "{{ rdp_user_home }}/archive/openmrs.xtrabackup.7z.md5"

  - sourceFile: "{{ rdp_backup_db_dir }}/dhis/dhis.pgdump.7z"
    targetFile: "{{ rdp_user_home }}/archive/dhis.pgdump.7z"

  - sourceFile: "{{ rdp_backup_db_dir }}/dhis/dhis.pgdump.7z.md5"
    targetFile: "{{ rdp_user_home }}/archive/dhis.pgdump.7z.md5"

rdp_restore_dbs:
  - restoreId: "openmrs"
    backupType: "xtrabackup"
    mysqlRootUser: "root"
    mysqlContainerPort: "3109"
    mysqlContainerTimezone: "UTC"
    restoreFilePassword: "Test1234"
    restoreFilePath: "{{ rdp_user_home }}/archive/openmrs-vagrant-test.xtrabackup.7z"

  - restoreId: "dhis"
    backupType: "pgdump"
    postgresUser: "dhis"
    postgresPassword: "dhis"
    postgresDatabase: "dhis"
    postgresContainerPort: "5532"
    postgresContainerImage: "postgis/postgis:12-3.4"
    restoreFilePassword: "Test1234"
    restoreFilePath: "{{ rdp_user_home }}/archive/dhis.pgdump.7z"

rdp_petl_config:
  petl:
    homeDir: "{{ rdp_petl_home }}"
    datasourceDir: "{{ rdp_petl_home }}/datasources"
    jobDir: "{{ rdp_petl_home }}/jobs"
    startup:
      exitAutomatically: true
  logging:
    level:
      root: "WARN"
      org.pih: "INFO"
  spring:
    datasource:
      platform: "h2"
      driver-class-name: "org.h2.Driver"
      url: "jdbc:h2:file:{{ rdp_petl_home }}/petl.db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE"
      username: "sa"
      password: "Test123"
      data: "classpath:schema-h2.sql"
    jpa:
      hibernate:
        ddl-auto: "none"
    quartz:
      job-store-type: "memory"
    h2:
      console:
        enabled: "true"
        path: "/h2"