rdp_backup_mysql_backup_file_path: "{{ rdp_backup_target_dir }}/openmrs-vagrant-test.xtrabackup.7z"
rdp_backup_cron_hour: "14"
rdp_backup_cron_minute: "52"

rdp_restore_dbs:
  - restoreId: "openmrs"
    backupType: "xtrabackup"
    mysqlRootUser: "root"
    mysqlContainerName: "omrs_restore"
    mysqlContainerPort: "3109"
    mysqlContainerTimezone: "UTC"
    mysqlDataDir: "{{ rdp_restore_db_dir }}/omrs_restore/mysql/data"
    mysqlRunDir: "{{ rdp_restore_db_dir }}/omrs_restore/mysql/run"
    restoreFilePassword: "Test1234"
    restoreFilePath: "{{ rdp_user_home }}/archive/openmrs-vagrant-test.xtrabackup.7z"
    restoreMd5FilePath: "{{ rdp_user_home }}/archive/openmrs-vagrant-test.xtrabackup.7z.md5"
    latestMd5FilePath: "{{ rdp_user_home }}/archive/openmrs-vagrant-test.xtrabackup.7z.md5.latest"

  - restoreId: "dhis"
    backupType: "pgdump"
    postgresUser: "dhis"
    postgresPassword: "dhis"
    postgresDatabase: "dhis"
    postgresContainerName: "dhis_restore"
    postgresContainerPort: "5532"
    postgresContainerImage: "postgis/postgis:12-3.4"
    restoreFilePassword: "Test1234"
    restoreFilePath: "{{ rdp_user_home }}/archive/dhis.pgdump.7z"
    restoreMd5FilePath: "{{ rdp_user_home }}/archive/dhis.pgdump.7z.md5"
    latestMd5FilePath: "{{ rdp_restore_db_dir }}/dhis/dhis.pgdump.7z.md5.latest"
