rdp_backup_dbs:
  - backupId: "rdpkirehetest"
    backupType: "xtrabackup"
    mysqlUser: "root"
    mysqlPassword: "root"
    mysqlDataDir: "/var/lib/mysql"
    mysqlRunDir: "/var/run/mysqld"
    targetDataDir: "{{ rdp_backup_db_dir }}/openmrsData"
    backupFilePassword: "Test1234"
    backupFilePath: "{{ rdp_backup_db_dir }}/rdpkirehetest.xtrabackup.7z"
    backupInstallMode: "native"

rdp_transfer_files:
  - sourceFile: "{{ rdp_backup_db_dir }}/*.7z"
    targetFile: "{{ rdp_user }}@{{ rdp_transfer_destination_host }}:{{ rdp_user_home }}/data/"
  - sourceFile: "{{ rdp_backup_db_dir }}/*.md5"
    targetFile: "{{ rdp_user }}@{{ rdp_transfer_destination_host }}:{{ rdp_user_home }}/data/"