rdp_backup_dbs:
  - backupId: "openmrs"
    backupType: "xtrabackup"
    mysqlUser: "root"
    mysqlPassword: "root"
    mysqlDataDir: "/var/lib/mysql"
    mysqlRunDir: "/var/run/mysqld"
    targetDataDir: "{{ rdp_backup_db_dir }}/openmrsData"
    backupFilePassword: "Test1234"
    backupFilePath: "{{ rdp_backup_db_dir }}/openmrs.xtrabackup.7z"
    backupInstallMode: "native"

rdp_transfer_files:
  - sourceFile: "{{ rdp_backup_db_dir }}/openmrs.xtrabackup.7z"
    targetFile: "{{ rdp_user_home }}/archive/openmrs.xtrabackup.7z"
  - sourceFile: "{{ rdp_backup_db_dir }}/openmrs.xtrabackup.7z.md5"
    targetFile: "{{ rdp_user_home }}/archive/openmrs.xtrabackup.7z.md5"
