- name: Base setup
  include_role: name=base_setup public=true

- name: Add backup script
  template: src=backup.sh dest={{ rdp_bin_dir }}/backup.sh owner={{ rdp_user }} group={{ rdp_user_group }} mode=0755

- name: Add backup configuration for each MySQL Xtrabackup
  template: src=xtrabackup.env dest={{ rdp_bin_dir }}/{{ item.backupId }}-backup.env mode=preserve
  with_items:
    - "{{ rdp_backup_dbs }}"
  when: item.backupType == "xtrabackup"

- name: Add backup scripts for each Postgres dump
  template: src=pgdump.env dest={{ rdp_bin_dir }}/{{ item.backupId }}-backup.env mode=preserve
  with_items:
    - "{{ rdp_backup_dbs }}"
  when: item.backupType == "pgdump"

- name: Add appropriate lines to backup.sh
  lineinfile: dest={{ rdp_bin_dir }}/backup.sh line='(echo "Backing up {{ item.backupId }}"; source {{ rdp_bin_dir }}/{{ item.backupId }}-backup.env; /bin/bash {{ rdp_scripts_dir }}/backup-{{ item.backupType }}.sh)'
  with_items:
    - "{{ rdp_backup_dbs }}"

- name: Setup cron
  cron: name="Backup DBs" minute="{{ rdp_backup_cron_minute }}" hour="{{ rdp_backup_cron_hour }}" weekday="{{ rdp_backup_cron_weekday }}" user="{{ rdp_backup_cron_user }}" job="exec >> {{ rdp_log_file }} 2>&1 && {{ rdp_bin_dir }}/backup.sh"
