- name: Base setup
  include_role: name=base_setup public=true

- name: Add transfer script
  template: src=transfer.sh dest={{ rdp_bin_dir }}/transfer.sh owner={{ rdp_user }} group={{ rdp_user_group }} mode=0755

- name: Add appropriate lines to transfer.sh
  lineinfile: dest={{ rdp_bin_dir }}/transfer.sh line='(echo "Transferring {{ item.sourceFile }} to {{ item.targetFile }}"; sudo -u {{ rdp_user }} /bin/bash -c "{{ rdp_scripts_dir }}/transfer-rsync.sh --sourceFile={{ item.sourceFile }} --targetFile={{ item.targetFile }}")'
  with_items:
    - "{{ rdp_transfer_files }}"

- name: Setup cron
  cron: name="Transfer files" minute="{{ rdp_transfer_cron_minute }}" hour="{{ rdp_transfer_cron_hour }}" weekday="{{ rdp_transfer_cron_weekday }}" user="{{ rdp_transfer_cron_user }}" job="exec >> {{ rdp_log_file }} 2>&1 && /usr/bin/flock -n {{ rdp_transfer_lock_file }} {{ rdp_bin_dir }}/transfer.sh"
